services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=Foment'
      - 'MYSQL_PASSWORD=Bonfim10@'
      - 'MYSQL_ROOT_PASSWORD=Bonfim10@'
      - 'MYSQL_USER=root'
    ports:
      - '3306'